### ISSUE TITLE
`download` command to fetch sdists from PyPI

### ISSUE THREAD

**Issue by jreese** [python-packaging/honesty#1]
Ideal command invocation:

`honesty download [--index-url=...] [--dest=<dir>] <package>[==<version>]`

Suggested API for fetching from Python code:

```python
def download(
    package: str,
    version: packaging.Version,
    dest: Path,
    *,
    index_url: str = "https://pypi.org/simple/"
) -> Path:
    ...
```
```
>>> from honesty import download

>>> download("aiosqlite", Version("0.10.0"), Path("/tmp/sdists/"))
PosixPath('/tmp/sdists/aiosqlite-0.10.0.tar.gz')
```

**Comment by thatch** [comment]
I hastily implemented this and cut version 0.1.0.

The command line matches your request (I assume this is the name of the flags used by pip?), but most other commands don't take --index-url and only use the env var.  It should also work with proxies, if that's something you need.

If the exit status is zero, then the name of the file(s) should be on stdout.  The API is in honesty.api, and you'll need to construct a Cache then use async calls.  It should be pretty straightforward.

If you don't *need* the dest dir, I would suggest not passing it, which will mean the filenames are just out of the cache dir and we trust you to not modify them.
